import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 0: Introduction to Physical AI',
      items: [
        'module0-intro/what-is-physical-ai',
        'module0-intro/embodied-intelligence',
        'module0-intro/humanoid-landscape',
        'module0-intro/prerequisites',
      ],
    },
    {
      type: 'category',
      label: 'Module 1: ROS 2 – Robotic Nervous System',
      items: [
        'module1-ros2/ros2-overview',
        'module1-ros2/nodes-topics',
        'module1-ros2/services-actions',
        'module1-ros2/rclpy-basics',
        'module1-ros2/urdf-humanoids',
        'module1-ros2/launch-files',
        'module1-ros2/exercises',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Gazebo & Unity – Digital Twin',
      items: [
        'module2-gazebo-unity/intro',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: NVIDIA Isaac AI-Robot Brain',
      items: [
        'module3-isaac/intro',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        'module4-vla/intro',
      ],
    },
    {
      type: 'category',
      label: 'Module 5: Capstone Project',
      items: [
        'module5-capstone/intro',
      ],
    },
    {
      type: 'category',
      label: 'Module 6: Hardware Setup',
      items: [
        'module6-hardware/intro',
      ],
    },
  ],
};

export default sidebars;
